//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SentimentAnalysisBuilder {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SentimentAnalysisBuilder.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dataset_ML_Common.csv.
        /// </summary>
        internal static string Dataset_ML_Common {
            get {
                return ResourceManager.GetString("Dataset_ML_Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dataset_ML_Movie.csv.
        /// </summary>
        internal static string Dataset_ML_Movie {
            get {
                return ResourceManager.GetString("Dataset_ML_Movie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dataset_ML_Shop.csv.
        /// </summary>
        internal static string Dataset_ML_Shop {
            get {
                return ResourceManager.GetString("Dataset_ML_Shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model_ML_Common.zip.
        /// </summary>
        internal static string Model_ML_Name_Common {
            get {
                return ResourceManager.GetString("Model_ML_Name_Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model_ML_Movie.zip.
        /// </summary>
        internal static string Model_ML_Name_Movie {
            get {
                return ResourceManager.GetString("Model_ML_Name_Movie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model_ML_Shop.zip.
        /// </summary>
        internal static string Model_ML_Name_Shop {
            get {
                return ResourceManager.GetString("Model_ML_Name_Shop", resourceCulture);
            }
        }
    }
}
